# Generated by Django 5.0.7 on 2024-07-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_alter_item_description_item_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
